// Auto-generated by scripts/pack-ui.js

export const getHtmlContent = (options: { title?: string; jsonUrl: string }) => `
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="./favicon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${options.title || "Ecosy API Explorer"}</title>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>

`;
