/* eslint-disable no-undef */
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

console.log("==> Building Swagger React UI...");
try {
  // Build the React app
  execSync('yarn run build', { 
    cwd: path.resolve(__dirname, '../swagger-ui-app'), 
    stdio: 'inherit' 
  });

  const htmlPath = path.resolve(__dirname, '../swagger-ui-app/dist/index.html');
  let htmlContent = fs.readFileSync(htmlPath, 'utf8');

  // Escape backslashes, backticks, and dollar signs from the minified HTML
  htmlContent = htmlContent.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');

  // We need to inject the dynamic options configuration BEFORE the script executes!
  // The React app expects window.API_JSON_URL.
  // In the raw HTML, we replace <head> with <head><script>...</script>!
  htmlContent = htmlContent.replace(
    '</head>',
    `  <script>
      // INJECTED CONFIGURATION (do not edit)
      window.API_JSON_URL = "\${options.jsonUrl}";
    </script>
</head>`
  );

  // We also replace <title> tag dynamically
  htmlContent = htmlContent.replace(/<title>(.*?)<\/title>/, '<title>${options.title || "Ecosy API Explorer"}</title>');

  // Create the TypeScript asset file
  const assetTsContent = `/* eslint-disable */\n// Auto-generated by scripts/pack-ui.js\n\nexport const getHtmlContent = (options: { title?: string; jsonUrl: string }) => \`\n${htmlContent}\n\`;\n`;

  const assetTsPath = path.resolve(__dirname, '../src/swagger-ui/assets.ts');
  fs.writeFileSync(assetTsPath, assetTsContent, 'utf8');

  console.log("==> Successfully packed UI into src/swagger-ui/assets.ts!");
} catch (e) {
  console.error("Failed to build Swagger UI:", e);
  process.exit(1);
}
